@php
  $editing = isset($technician);
  $parts = $editing ? preg_split('/\s+/', trim($technician->name), 2) : ['', ''];
  $firstName = old('first_name', $parts[0] ?? '');
  $lastName = old('last_name', $parts[1] ?? '');
  $selectedSkills = old('skills', $technician->skills ?? ['HVAC','Electrical','General Maint.']);
  $selectedCerts = old('certifications', $technician->certifications ?? ['EPA 608','HVAC-R Licensed']);
  $selectedZones = old('covered_zones', $technician->covered_zones ?? ['Zone B','Zone C']);
  $selectedDays = old('work_days', $technician->work_days ?? ['M','T','W','Th','F']);
@endphp
<form method="POST" action="{{ $editing ? route('technicians.update',$technician) : route('technicians.store') }}" enctype="multipart/form-data">
  @csrf @if($editing) @method('PUT') @endif
  <div class="panel border display-flex profile-photoupload-a-photo-jp-text">
    <div class="photo-upload-circle panel-div">@if($editing && $technician->photo)<img src="{{ $technician->photo_url }}" alt="Profile" style="width:100%;height:100%;object-fit:cover;border-radius:50%;">@else
      <svg aria-hidden="true" fill="none" height="29" viewbox="0 0 29 29" width="29"><path d="M23.9998 25.2V22.8C23.9998 21.527 23.4941 20.3061 22.5939 19.4059C21.6937 18.5057 20.4728 18 19.1998 18H9.5998C8.32677 18 7.10587 18.5057 6.20569 19.4059C5.30552 20.3061 4.7998 21.527 4.7998 22.8V25.2" stroke="#9CA3AF" stroke-width="2.4"></path><path d="M14.4006 13.2C17.0516 13.2 19.2006 11.051 19.2006 8.39999C19.2006 5.74902 17.0516 3.59999 14.4006 3.59999C11.7496 3.59999 9.60059 5.74902 9.60059 8.39999C9.60059 11.051 11.7496 13.2 14.4006 13.2Z" stroke="#9CA3AF" stroke-width="2.4"></path></svg>@endif<div class="photo-upload-plus"><svg aria-hidden="true" fill="none" height="8" viewbox="0 0 6 6" width="8"><path d="M2.02931 5.43069V7.49474e-06H3.40233V5.43069H2.02931ZM0.000479684 3.40185V2.02884H5.43116V3.40185H0.000479684Z" fill="white"></path></svg></div></div>
    <div class="ms-3"><h4 class="font-weight-bold code-text">Profile Photo</h4><p class="upload-a-photo-jpg-png-max-m-text">Upload a photo (JPG, PNG -- max 2 MB)</p><label class="btn-custom btn-outline-custom font-weight-bold cursor-pointer upload-photo-text" for="photo-upload">Upload Photo</label><input accept="image/png, image/jpeg" class="display-none" id="photo-upload" name="photo" type="file" /></div>
  </div>
  <div class="row g-4">
    <div class="column-full col-lg-7">
      <div class="panel code-detailscodestatusdisplay-text"><h4 class="section-header-title">PERSONAL INFORMATION</h4><div class="row g-4">
        <div class="column-full col-md-6"><label class="form-label-custom font-weight-bold code-text">First Name *</label><input name="first_name" value="{{ $firstName }}" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" placeholder="e.g. Jordan" type="text" required /></div>
        <div class="column-full col-md-6"><label class="form-label-custom font-weight-bold code-text">Last Name *</label><input name="last_name" value="{{ $lastName }}" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" placeholder="e.g. Williams" type="text" required /></div>
        <div class="column-full col-md-6"><label class="form-label-custom font-weight-bold code-text">Email Address *</label><input name="email" value="{{ old('email',$technician->email ?? '') }}" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" placeholder="j.williams@fieldops.com" type="email" /></div>
        <div class="column-full col-md-6"><label class="form-label-custom font-weight-bold code-text">Phone Number *</label><input name="phone" value="{{ old('phone',$technician->phone ?? '') }}" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" placeholder="+1 (555) 000-0000" type="text" /></div>
        <div class="column-full"><label class="form-label-custom font-weight-bold code-text">Employee ID</label><input name="employee_id" value="{{ old('employee_id',$technician->employee_id ?? '') }}" class="form-control-custom col-input" placeholder="Auto-generated if blank" type="text" /></div>
      </div></div>
      <div class="panel border role-accessrole-tech-i-juniort-text"><h4 class="section-header-title">ROLE &amp; ACCESS</h4>
        {{-- <div class="manage-usersall-work-ordersvie-text"><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Role *</label><div class="row m-0">@foreach($roles as $value=>$label)<div class="col-md-6 column-full mb-3"><label class="cursor-pointer tech-i-junior-text w-100"><input class="display-none" name="role" type="radio" value="{{ $value }}" @checked(old('role',$technician->role ?? 'senior')===$value) /><div class="role-btn">{{ $label }}</div></label></div>@endforeach</div></div> --}}
        <div class="manage-usersall-work-ordersvie-text"><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">App Access Level</label><select name="access_level" class="form-control-custom select-arrow-left fromfieldops-services-llc-text-alt-div-custom-input-custom"><option value="Field Technician (view own jobs only)" @selected(old('access_level',$technician->access_level ?? '')==='Field Technician (view own jobs only)')>Field Technician (view own jobs only)</option><option value="Supervisor">Supervisor</option><option value="Administrator">Administrator</option></select></div>
        <label class="display-flex cursor-pointer"><input name="invitation_sent" value="1" class="checkbox-custom display-none" type="checkbox" @checked(old('invitation_sent',$technician->invitation_sent ?? true)) /><span class="checkbox-box"></span><span> Send invitation email with app login link </span></label>
      </div>
      <div class="panel code-detailscodestatusdisplay-text"><h4 class="section-header-title">EQUIPMENT ASSIGNMENT</h4><div class="manage-usersall-work-ordersvie-text"><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Assign Vehicle</label><select name="vehicle" class="form-control-custom select-arrow-left fromfieldops-services-llc-text-alt-div-custom-input-custom"><option value="">-- Select available van --</option>@foreach(['Van-01','Van-02','Van-03'] as $v)<option @selected(old('vehicle',$technician->vehicle ?? '')===$v) value="{{ $v }}">{{ $v }}</option>@endforeach</select></div><div class="super-admin-userssystempermis-text"><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Diagnostic Kit</label><select name="diagnostic_kit" class="form-control-custom select-arrow-left fromfieldops-services-llc-text-alt-div-custom-input-custom"><option value="">-- Select kit --</option>@foreach(['Kit-01','Kit-02','Kit-03'] as $k)<option @selected(old('diagnostic_kit',$technician->diagnostic_kit ?? '')===$k) value="{{ $k }}">{{ $k }}</option>@endforeach</select></div></div>
    </div>
    <div class="column-full col-lg-5">
      {{-- <div class="panel border role-accessrole-tech-i-juniort-text"><h4 class="section-header-title">SKILLS &amp; CERTIFICATIONS</h4><div class="fromfieldops-services-llc-text"><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Trade Skills *</label><div>@foreach($skillsList as $skill)<label class="cursor-pointer topbar-left-label"><input name="skills[]" value="{{ $skill }}" class="display-none" type="checkbox" @checked(in_array($skill,$selectedSkills)) /><div class="pill-btn">{{ $skill }}</div></label>@endforeach</div></div><div><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Certifications</label><div class="display-flex epa-verifiednate-certifiedh-text">@foreach($certificationList as $cert)<div class="display-flex total-text-primary"><label class="display-flex sksarah-kimadmin-text cursor-pointer"><input name="certifications[]" value="{{ $cert }}" class="checkbox-custom display-none" type="checkbox" @checked(in_array($cert,$selectedCerts)) /><span class="checkbox-box"></span><span>{{ $cert }}</span></label>@if(in_array($cert,['EPA 608','HVAC-R Licensed']))<span class="badge-verified">Verified</span>@endif</div>@endforeach</div></div></div> --}}
      {{-- <div class="panel territory-scheduleprimary-zone-text"><h4 class="section-header-title">TERRITORY &amp; SCHEDULE</h4><div class="super-admin-userssystempermis-text"><label class="form-label-custom font-weight-bold custom-d-block code-text">Primary Zone *</label><select name="primary_zone" class="form-control-custom select-arrow-left fromfieldops-services-llc-text-alt-div-custom-input-custom">@foreach($zones as $zone)<option value="{{ $zone }}" @selected(old('primary_zone',$technician->primary_zone ?? 'Zone A -- SF Downtown')===$zone)>{{ $zone }}</option>@endforeach</select></div><div class="manage-usersall-work-ordersvie-text"><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Also covers (optional)</label><div class="display-flex manage-usersall-work-ordersvie-text-div-custom-primary">@foreach(array_slice($zones,1) as $zone)<label class="cursor-pointer topbar-left-label"><input name="covered_zones[]" value="{{ $zone }}" class="display-none" type="checkbox" @checked(in_array($zone,$selectedZones)) /><div class="pill-btn">+ {{ str_replace('Zone ','Zone ',$zone) }}</div></label>@endforeach</div></div> --}}
        <div><label class="form-label-custom font-weight-bold custom-d-block manage-usersall-work-ordersvie-text-label-custom">Work Schedule</label><div class="display-flex mtwthfsasu-text">@foreach($days as $key=>$day)<input name="work_days[]" value="{{ $key }}" class="display-none" id="day-{{ strtolower($key) }}" type="checkbox" @checked(in_array($key,$selectedDays)) /><label class="day-picker-btn inactive-text" for="day-{{ strtolower($key) }}">{{ $key }}</label>@endforeach</div><div class="row g-3"><div class="col-md-6 column-full super-admin-userssystempermis-text"><label class="form-label-custom font-weight-bold code-text">Start Time</label><input name="start_time" value="{{ old('start_time',$technician->start_time ?? '07:00') }}" class="custom-date-input custom-pr form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" type="time" /></div><div class="col-md-6 column-full super-admin-userssystempermis-text"><label class="form-label-custom font-weight-bold code-text">End Time</label><input name="end_time" value="{{ old('end_time',$technician->end_time ?? '16:00') }}" class="custom-date-input custom-pr form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" type="time" /></div></div></div>
      </div>
    </div>
  </div>
  <div class="panel mt-4"><h4 class="section-header-title">STATUS & NOTES</h4><div class="row g-4"><div class="col-md-4"><label class="form-label-custom font-weight-bold code-text">Status</label><select name="status" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom"><option @selected(old('status',$technician->status ?? 'Active')==='Active')>Active</option><option @selected(old('status',$technician->status ?? '')==='On Site')>On Site</option><option @selected(old('status',$technician->status ?? '')==='En Route')>En Route</option><option @selected(old('status',$technician->status ?? '')==='Scheduled')>Scheduled</option><option @selected(old('status',$technician->status ?? '')==='Overdue')>Overdue</option><option @selected(old('status',$technician->status ?? '')==='Inactive')>Inactive</option></select></div><div class="col-md-4"><label class="form-label-custom font-weight-bold code-text">Rating</label><input name="rating" value="{{ old('rating',$technician->rating ?? 0) }}" min="0" max="5" step="0.1" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom" type="number" /></div><div class="col-md-4"><label class="display-flex cursor-pointer mt-4"><input name="active" value="1" class="checkbox-custom display-none" type="checkbox" @checked(old('active',$technician->active ?? true)) /><span class="checkbox-box"></span><span> Active technician </span></label></div><div class="col-12"><label class="form-label-custom font-weight-bold code-text">Notes</label><textarea name="notes" rows="4" class="form-control-custom fromfieldops-services-llc-text-alt-div-custom-input-custom">{{ old('notes',$technician->notes ?? '') }}</textarea></div></div></div>
  <div class="display-flex backsave-text"><a class="btn-custom btn-outline-custom font-weight-bold back-action text-decoration-none" href="{{ route('technicians.index') }}">Cancel</a><button class="btn-custom btn-primary-custom font-weight-bold inv-text" type="submit">{{ $editing ? 'Update' : 'Save' }}</button></div>
</form>
